version: '3'

services:
  redis-master:
    image: redis:alpine
    ports:
      - 6379:6379

  redis-slave:
    image: redis:alpine
    depends_on:
      - redis-master
    command: redis-server --slaveof redis-master 6379

  redis-sentinel:
    build: ./sentinel
    depends_on:
      - redis-master
