version: '3'

services:
  redis-master:
    image: redis:alpine

  redis-slave:
    image: redis:alpine
    depends_on:
      - redis-master
    command: redis-server --slaveof redis-master 6379

  redis-sentinel:
    build: ./sentinel
    ports:
      - 26379-26479:26379
    depends_on:
      - redis-master
