version: '3'

services:
  redis-master:
    image: redis:alpine
    ports:
      - 6379:6379

  redis-slave:
    image: redis:alpine
    ports:
      - 6380-6381:6379
    depends_on:
      - redis-master
    command: redis-server --slaveof redis-master 6379

  redis-sentinel:
    build: ./sentinel
    ports:
      - 26379-26381:26379
    depends_on:
      - redis-master
